// AUTH TYPES
export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const REG_REQUEST = 'REG_REQUEST';
export const TOKEN_REVOKE = 'TOKEN_REVOKE';
export const FORGOT_PASS = 'FORGOT_PASS';

// PRODUCTS TYPES
export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const SET_PRODUCTS_DATA = 'SET_PRODUCTS_DATA';
export const SET_CATEGORY_ID_DATA = 'SET_CATEGORY_ID_DATA';
export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO';

// CATEGORIES TYPES
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_CATEGORIES_DATA = 'SET_CATEGORIES_DATA';
export const SET_CURRENT_CATEGORY_DATA = 'SET_CURRENT_CATEGORY_DATA';

// BASKET TYPES
export const ADD_PRODUCTS_IN_BASKET_DATA = 'ADD_PRODUCTS_IN_BASKET_DATA';
export const POST_PRODUCT_IN_BASKET = 'POST_PRODUCT_IN_BASKET';
export const SET_ACTIVE_BASKET_DATA = 'SET_ACTIVE_BASKET_DATA';
export const SET_MULTI_BASKET_DATA = 'SET_MULTI_BASKET_DATA';
export const GET_MULTI_BASKET = 'GET_MULTI_BASKET';
export const GET_PRODUCTS_BASKET = 'GET_PRODUCTS_BASKET';
export const CREATE_BASKET = 'CREATE_BASKET';
export const DELETE_BASKET = 'DELETE_BASKET';
export const DELETE_PRODUCT_IN_BASKET = 'DELETE_PRODUCT_IN_BASKET';
export const RENAME_BASKET_DATA = 'RENAME_BASKET_DATA';
export const PUT_RENAME_BASKET = 'PUT_RENAME_BASKET';
export const PUT_CHANGE_QUANTITY_PRODUCT = 'PUT_CHANGE_QUANTITY_PRODUCT';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const GET_BASKET_SUM = 'GET_BASKET_SUM';
export const DELETE_PRODUCT_IN_MULTI_BASKET = 'DELETE_PRODUCT_IN_MULTI_BASKET';

// ACCOUNT TYPES
export const SET_ORG_DATA = 'SET_ORG_DATA';
export const GET_ORG = 'GET_ORG';
export const SET_ADDRESSES_DATA = 'SET_ADDRESSES_DATA';
export const GET_ADDRESSES = 'GET_ADDRESSES';
export const GET_CONTACT = 'GET_CONTACT';

// ORDER TYPES
export const POST_CREATE_ORDER = 'POST_CREATE_ORDER';
export const SET_ORDERS_DATA = 'SET_ORDERS_DATA';
export const GET_ORDERS = 'GET_ORDERS';
export const SET_ORDER_HISTORY_DATA = 'SET_ORDER_HISTORY_DATA';
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
export const SET_ORDER_ID_DATA = 'SET_ORDER_ID_DATA';
export const POST_REPEAT_ORDER = 'POST_REPEAT_ORDER';


export const GET_NAME = 'GET_NAME';
export const SET_POST_NAME = 'SET_POST_NAME';
export const SET_POST_PASS = 'SET_POST_PASS';
