// UI TYPES
export const LOADING = 'LOADING';
export const SET_WIDTH = 'SET_WIDTH';
export const SET_INFINITY_SCROLL_BUSY = 'SET_INFINITY_SCROLL_BUSY';

// AUTH TYPES
export const SET_TOKEN = 'SET_TOKEN';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';

// PRODUCTS TYPES
export const DEFAULT_OFFSET = 'DEFAULT_OFFSET';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_CATEGORY_ID = 'SET_CATEGORY_ID';
export const SET_PRODUCT_SORT = 'SET_PRODUCT_SORT';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_COLUMN_SELECTOR = 'SET_COLUMN_SELECTOR';

// CATEGORIES TYPES
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';

// BASKET TYPES
export const ADD_PRODUCTS_IN_BASKET = 'ADD_PRODUCTS_IN_BASKET';
export const SET_ACTIVE_BASKET = 'SET_ACTIVE_BASKET';
export const SET_MULTI_BASKET = 'SET_MULTI_BASKET';
export const ADD_BASKET_IN_MULTI_BASKET = 'ADD_BASKET_IN_MULTI_BASKET';
export const RENAME_BASKET = 'RENAME_BASKET';
export const SET_BASKET_SUM = 'SET_BASKET_SUM';

// ACCOUNT TYPES
export const SET_ORG = 'SET_ORG';
export const SET_ADDRESSES = 'SET_ADDRESSES';

// ORDERS TYPES
export const SET_ORDERS = 'SET_ORDERS';
export const SET_ORDER_HISTORY = 'SET_ORDER_HISTORY';
export const SET_ORDER_ID = 'SET_ORDER_ID';

export const SET_CONTACT = 'SET_CONTACT';
export const SET_NAME = 'SET_NAME';
export const SET_EMAIL = 'SET_EMAIL';
